/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Admiral Tributon (https://sketchfab.com/doctor10)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cas-class-assault-carrier-76c3a276eee64ae2bd83a8ead67880db
title: CAS Class Assault Carrier
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function CovenantCarrier(props) {
  const { nodes, materials } = useGLTF("/covenant_carrier/scene.gltf");
  const carrierRef = useRef();
  useFrame(() => {
    if (carrierRef.current.position.x >= -1.65)
      carrierRef.current.position.x += -0.003;
  });
  return (
    <group {...props} dispose={null} ref={carrierRef}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0.85, 0, -1.1]}
        scale={0.0007}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[260.64, 156.97, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.58}
          >
            <mesh
              geometry={nodes.cas_carrier_stern_main_0.geometry}
              material={materials.stern_main}
            />
            <mesh
              geometry={nodes.cas_carrier_building_lights_main_0.geometry}
              material={materials.building_lights_main}
            />
            <mesh
              geometry={nodes.cas_carrier_bow_main_0.geometry}
              material={materials.bow_main}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/covenant_carrier/scene.gltf");
