/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Controller(props) {
  const { nodes, materials } = useGLTF("/xbox_controller/xbox_controller.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id62.geometry}
        material={materials["89"]}
        position={[-0.2, -0.17, 0]}
        rotation={[0.3, -Math.PI / 2, 0]}
        scale={0.08}
        castShadow
      />
    </group>
  );
}

useGLTF.preload("/xbox_controller/xbox_controller.glb");
